### ISSUE TITLE
OSX installation, testing, updating of the readme

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/VarianceComponentsHDFE.jl#1]

**Comment by jlperla** [comment]
Adam previously said that there was a warning of `tarball for osx build gives a warning to user that github is not a trusted developer `   so we need to be careful to make sure the steps are clear.  If it is just a warning that doesn't require action, just say "ignore the warning", etc.

**Comment by ajozefiak** [comment]
I can make a PR proposed changes to the readme later tonight. In summary, the solution entails the user double-clicking on the executable (haven't tested the command line since it wasn't responding at all initially) and seeing a warning that the app can't be trusted, and then going into the security settings on the mac and authorizing the vchdfe app.
