### ISSUE TITLE
Does adding controls work at current version?

### ISSUE THREAD

**Issue by Alalalalaki** [HighDimensionalEconLab/VarianceComponentsHDFE.jl#37]
I cannot replicate the estimation with controls in [Typical Julia Workflow](https://highdimensionaleconlab.github.io/VarianceComponentsHDFE.jl/dev/Package/#Typical-Julia-Workflow). The code breaks with following error.  

<img width="1072" alt="スクリーンショット 2022-04-21 13 32 54" src="https://user-images.githubusercontent.com/31154974/164372633-3bb2f6c1-76fa-48d4-a1da-d489876356d6.png">

Also I wonder if controls can have both dummy and non-dummy variables under this "partialling out" method?

**Comment by jlperla** [comment]
Thanks for the report. @Alim-faraji, is this bug reproducible?

**Comment by Alim-faraji** [comment]
I could not reproduce this error. However, I realized some of the commands in [Typical Julia Workflow](https://highdimensionaleconlab.github.io/VarianceComponentsHDFE.jl/dev/Package/#Typical-Julia-Workflow) were out of date. I updated them. Can you try following the instructions again?

**Comment by Alalalalaki** [comment]
@Alim-faraji No the error remains. It works well with  no controls but throws the above error when adding controls. I have tried running the code under both Julia 1.6 and 1.7.

**Comment by Alim-faraji** [comment]
Just to make sure, this line throws the error? 
`θ_first, θ_second, θCOV = leave_out_KSS(y,id,firmid; controls)`

**Comment by Alalalalaki** [comment]
Yes. I guess it's about this line `P = AmgOperator(ruge_stuben(xx),buff)`.

**Comment by Alim-faraji** [comment]
I suspect there must be something missing in the dependencies. We are going to clean them up and get a new release out next week. I reply to this post whenever we finished.

**Comment by Alim-faraji** [comment]
I made some changes to `project.toml` file, and I think if you pull and try again, you won't see any errors.

**Comment by Alalalalaki** [comment]
Yes it works now. And I confirm that the controls work for both dummy and nondummy variables.

But one thing I am curious about is that the variance due to the controls are not reported in the results, perhaps because they are simply partialled out. But is it also included in the total variance that is used to calculate the  "Fraction of Variance explained by  person-firm Effects" in the result? Also if I am also interested in how large is the variance component of the controls, how can I calculate it? And more importantly, is this component also biased and subject to KSS correction?

**Comment by Alim-faraji** [comment]
Glad to hear it works now! 

Control variables are partialled out and their variance is not part of the total variance. So in a model with no error term `y = alpha + psi + c` where `c` is a control, and `alpha` and `psi` are fixed effects, `alpha` and `psi` should explain total variance. 

I don't think KSS correction is applicable to the variance component of controls, and you can just simply calculate their variance, but @rsaggio87 knows better.

**Comment by rsaggio87** [comment]
hi. If controls are ``low dimensional" then computing plug-in version of the variance components associated with the controls is perfectly ok, i.e. you don't need to run the KSS correction.

**Comment by Alalalalaki** [comment]
@Alim-faraji Sorry for late reply. You mean I can use the code in "Partialling out controls" to calculate the variance for `X[:,N+J:end]*beta[N+J:end]`, right?

**Comment by Alalalalaki** [comment]
@rsaggio87 Thanks so much for answering. How low do you mean ``low dimensional"? Of course say a dozen but how about 100? Or just <<N? And more importantly why is the plug-in variance and covariances not biased in this case? Is it because low dimension would largely reduce the bias? What if there is strong sorting between covariates and firm effects or job effects?

Btw, I wonder why is it the custom in the AKM literature to add year effects and age as controls? I can understand the year effects because it is not something we focus on. But why controlling for age? And why not also adding education, occupation, sex, and many else? The reason I ask this is because one research question I am curious about is that what exactly cause the firm and worker sorting. Can I add, say education, experience, and occupation, to covariates and calculate the covariance terms and see to what share of the sorting is accounted by these observed variables and to what share is accounted by those unobserved?

**Comment by rsaggio87** [comment]
I would say that if your covariates are things like year effects, age, education, then you can safely use PI equivalents for their variance components. The reason is that the associated coefficient for each covariate here is consistent and finite sample biases in the resulting variance component are unlikely to be first order. The vignette presents some of these ideas (https://github.com/rsaggio87/LeaveOutTwoWay/blob/master/doc/VIGNETTE.pdf). If the component of interest is, say, the covariance of firm effects and education*b where b is the coefficient on education, then you need KSS correction. 

Typically, the object after having estimated an AKM equation is to assess the importance of firms in setting wages. This is why the targets are typically variance of firm effects and covariance of firm and worker effects. Age, year, education, are used simply as controls and therefore are typically treated as nuisance when calculating variance components. However, as you correctly pointed, you can definitely expand upon this framework and see what X's could explain sorting!

**Comment by Alalalalaki** [comment]
@rsaggio87 I see. It's all about the finite sample biases. Thanks a lot for explaining.

**Comment by Alim-faraji** [comment]
@Alalalalaki I'm not sure to which part of the code are you referring as `Partiallling out controls'. However, I doubt what you said is the way to do it, because `beta' contains only fixed effect estimates and have only `N+J' elements. I think, instead, using the built-in Julia variance function should do the work.

**Comment by Alalalalaki** [comment]
@Alim-faraji I mean the below part. Because I don't see the package result incorporates any of this part, I thought I have to redo it to get the variance and covariance terms for controls?

```python
    if controls != nothing  
        println("\nPartialling out controls...")
        NT = size(y,1)
        J = maximum(second_id)
        N = maximum(first_id)
        K = size(controls,2)
        nparameters = N + J + K

        D = sparse(collect(1:NT),first_id,1)
        F = sparse(collect(1:NT),second_id,1)
        S= sparse(1.0I, J-1, J-1)
        S=vcat(S,sparse(-zeros(1,J-1)))
        X = hcat(D, -F*S, controls)

        #My best shot is to wrap AMG as LinearOperator
        buff = zeros(size(X,2))  
        xx = X'*X       
        P = AmgOperator(ruge_stuben(xx),buff)
        xy=X'*y
        beta, stats = Krylov.cg(xx,[xy...]; M = P , rtol = 1e-6, itmax = 300)

        y=y-X[:,N+J:end]*beta[N+J:end]
        controls = nothing
        println("Partialling out completed.")
    end
```

**Comment by Alim-faraji** [comment]
I see what you mean now. As you can see in the code, the control variables are partialled out before calculating the KSS corrected components, and as such, they are not included in the output. The reason is it's not implemented in the current version. However, to answer your question: yes! You can use `X[:, N+J:end]` and `beta[N+J:end]` vectors as calculated above (PI version) to compute variance and covariance components. However, the covariance between fixed effects that need KSS correction (like firm-effects) and control variables are more tricky as far as I understand and require correction, but it's not implemented yet.

**Comment by Alalalalaki** [comment]
@Alim-faraji Thanks for your clarification. I look forward to the future implementation on the correction of the covariance terms between controls and firm/worker effects.
